language: ruby
before_install: gem install bundler
bundler_args: --without development

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3

# Container-based infra for builds that start faster.
sudo: false
